### PR TITLE
add bulkDelete function

### PR DESCRIPTION
**Pull request by kmccormick**
Copying the bulk create/update functions recently added to make a bulkDelete version.

### CODE REVIEW

**Comment by reynolek** [comment]
Since you mentioned you copied the functions, I just want to make sure you have attempted a `bulkDelete` and had it succeed?

**Comment by kmccormick** [comment]
Actually, not exactly. I was trying to delete tickets, which apparently is just plain not supported by the API (confirmed in the docs). I did get a well-formed error message from the API that Ticket objects don't support delete... :(

**Comment by reynolek** [comment]
Ah that's lame. Alright well if you got a well formatted response that's enough for me to believe that it will work.

**Comment by reynolek** [comment]
Thank you for your contribution!

**Pull request merged**
