### PR TITLE
PR - Get Attachment

### PR DESCRIPTION
**Pull request by SirPoot-**
This is my first PR and is related to #92.. Go easy. Please tell me if I am doing something wrong or I could improve something.

**USAGE**

```
        require_once __DIR__ . '/autoload.php';

        use \ATWS;
        use \ATWS\AutotaskObjects;

        $username           = 'INSERT USERNAME HERE';
        $password           = 'INSERT PASSWORD HERE';

        $postAuthOpts = array(
            'login' => $username,
            'password' => $password,
            'trace' => 1,   // Allows us to debug by getting the XML requests sent
        );

        $opts = array('trace' => 1);
        $authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
        $client = new ATWS\Client($authWsdl, $opts);
        $zoneInfo = $client->getZoneInfo($username);

        $wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
        $client = new ATWS\Client($wsdl, $postAuthOpts);
        
        $ticketId = 225975;
        $attachmentInfo = new \ATWS\AutotaskObjects\Query('AttachmentInfo');
        $parentidQueryfield = new \ATWS\AutotaskObjects\QueryField('parentid');
        $parentidQueryfield->addExpression('equals',$ticketId);
        $attachmentInfo->addField($parentidQueryfield);
        $attachments = $client->query($attachmentInfo);
        $attachments = (count($attachments) > 1 ? $attachments : [$attachments]);
        foreach ($attachments as $attachment)
        {
            $result = $client->GetAttachment($attachment);
            $save = file_put_contents($result->GetAttachmentResult->Info->FullPath, $result->GetAttachmentResult->Data);
        }
```

### CODE REVIEW

**Comment by reynolek** [comment]
Code itself looks good to me.

I think it may be a good idea to create a new file at the root thats named something like `get_attachment_example.php` and put your nicely written example code into it.

I should probably eventually put together an examples folder to contain them, but that's a battle for another day.

**Comment by SirPoot-** [comment]
Please hold off on merging. @christophercygnet found a problem. I requested he confirms my fix works before modifing this PR.

**Comment by SirPoot-** [comment]
@christophercygnet confirmed the issue is fixed. I added the example file, per your request. Ready to be merged. :)

**Comment by reynolek** [comment]
Merged, and released the code in v0.1.12

**Pull request merged**
