### PR TITLE
Credential check

### PR DESCRIPTION
**Pull request by sulfurcode**
Added a function that checks credentials and returns true or false.

Also added a Soap Exception handler to the _call function

### CODE REVIEW

**Comment by sulfurcode** [comment]
Apologies for the double commit, accidentally added a load of IDE config files!

**Comment by reynolek** [comment]
Overall here I am not sure this change should go into the code.

The goal of this client is to be a wrapper around SOAP and Autotask's objects so that people don't have to manipulate xml or read documentation to figure out what variables you can set on the Autotask objects

This type of code would be something you would put into a second class that implements this client.

For example, in our OpenDNS implementation, we have a different class that implements `autotask-php` as an internal soap client. This class has an `init` function that does what your `validCaredentials` function does.

So something like this:

```
<?php
// require the autotask-php soap client where it is in your code

class AutotaskClient
{
    protected $client;

    private $username;
    private $password;
    private $zoneInfoWsdl = 'zone wsdl url';
    private $wsdl;

    function __construct($username, $password)
    {
        // set the private username and password
    }

    function init()
    {
        // return true if the auth check passes by checking Account 0 or Ticket or whatever
    }
}

```

Make sense?

**Comment by sulfurcode** [comment]
That’s fair enough. 

Hopefully someone will find it useful.

Thanks

**Comment by sulfurcode** [comment]
Is it worth handling the Soap Exception in the call function though?

**Comment by reynolek** [comment]
I dont think it is -- the reason mostly being any error handling should happen at the client use point.

Particularly in your solution, anyone that is currently catching the errors would suddenly break due to the error now being returned, so the result of the call looks successful despite the fact that it was not.

**Comment by reynolek** [comment]
So in the case of writing the wrapping client, you could easily handle errors however you wanted to -- throw custom exceptions that contain the important info of the SoapFault for example, and then be able to handle different errors different ways.

**Pull request closed without merging**
